---
     - name: This playbook is dedicated to taking backup to remote server
       block:

        - name: Creating a file with script to execute
          become: true
          copy:
            dest: "{{cronjob_log_folder}}/{{item.name}}.sh"
            mode: 0755
            content: |
              CURRENT_TIME=$(date +"%Y%m%d_%H%M")
              echo "Execution Started at: $CURRENT_TIME" >> {{cronjob_log_folder}}/{{item.name}}.log
              RESULT_LOG=$(rsync -av -e ssh {{ inventory_hostname }}:{{ item.path }} {{cronjob_log_folder}}/backups/{{ inventory_hostname }})
              echo "$RESULT_LOG" >> {{cronjob_log_folder}}/{{item.name}}.log
              CURRENT_TIME=$(date +"%Y%m%d_%H%M")
              echo "Execution Completed at: $CURRENT_TIME" >> {{cronjob_log_folder}}/{{item.name}}.log
              /usr/bin/python {{cronjob_log_folder}}/create_csv.py "{{ item.path }}" "Success" "{{ server_ip }}" "{{cronjob_log_folder}}/{{ inventory_hostname }}.csv"
              /usr/bin/python {{cronjob_log_folder}}/create_html.py "{{ inventory_hostname }}" "{{cronjob_log_folder}}/{{ inventory_hostname }}.csv" "{{cronjob_log_folder}}/html/{{ inventory_hostname }}.html" "{{cronjob_log_folder}}/servers.csv"
              FILE="{{cronjob_log_folder}}/html/index.html"
              FILE_CONTENT="SERVER IS READY TO GO!"
              if [ -f "$FILE" ]; then
                  if grep -q "$FILE_CONTENT" "$FILE"; then
                      rm $FILE
                      CURRENT_TIME=$(date +"%Y%m%d_%H%M")
                      echo "$CURRENT_TIME $FILE exists. Deleting and updating. " >> {{cronjob_log_folder}}/{{item.name}}.log
                      cp html/{{ inventory_hostname }}.html $FILE
                  fi
              else 
                  CURRENT_TIME=$(date +"%Y%m%d_%H%M")
                  echo "$CURRENT_TIME $FILE does not exist. Creating new file." >> {{cronjob_log_folder}}/{{item.name}}.log
                  cp html/{{ inventory_hostname }}.html $FILE
              fi
              exit

        - name: Creates an schedule #  crontab -l
          cron:
            name: "ScriptExecute-{{item.name}}"
            hour: "*/{{item.hours}}"
            minute: 0
            job: "{{cronjob_log_folder}}/{{item.name}}.sh"
