---
- name: This playbook is dedicated to install dependencies
  hosts: bk_main_server
  tasks:
    - name: Executing script to collections
      shell: ansible-galaxy collection install community.docker

    - name: Executing posix
      shell: ansible-galaxy collection install ansible.posix



          

          