---
- name: This playbook is to set the schedule
  hosts: bk_main_server
  tasks:

    - name: Creating a new folder
      become: true
      file:
        path: "{{cronjob_log_folder}}"
        state: directory
 
    - name: Creating a file with script to execute
      become: true
      copy:
        dest: "{{cronjob_log_folder}}/exec.sh"
        mode: 0755
        content: |
          CURRENT_TIME=$(date +"%Y%m%d_%H%M")
          echo "Executed successfully at: $CURRENT_TIME" >> {{cronjob_log_folder}}/log.log

    - name: Creates an schedule
      cron:
        name: "BookScriptExecute"
        day: "*/1"
        job: "{{cronjob_log_folder}}/exec.sh"

          