---
- hosts: pentahost24
  
  tasks:

    - name: Creating a file with script to execute  
      become: true
      copy:
        dest: "{{cronjob_log_folder}}/html/index.html"
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta http-equiv="X-UA-Compatible" content="IE=edge">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Sample</title>
          </head>
          <body>
              SERVER IS READY TO GO!
          </body>
          </html>

    - name: Deploy Server Page
      community.docker.docker_container:
        name: serverpage
        image: "nginx:alpine"
        ports:
          - "8080:80"
        volumes:
          - "{{cronjob_log_folder}}/html:/usr/share/nginx/html"
        restart_policy: always